Add activities for status change [SCI-4827]
biosistemika/scinote-web pull request #2769
Opened 2020-08-04 14:41 UTC by urbanrotnik

Jira ticket: [SCI-4827](https://biosistemika.atlassian.net/browse/SCI-4827)

2020-08-25 12:53 UTC, aignatov-bio requested changes

2020-08-25 12:53 UTC, aignatov-bio commented on config/initializers/extends.rb
> +    cosign_task: 148,
Why it here?

2020-08-27 09:28 UTC, radiokills commented on app/controllers/my_modules_controller.rb
> +    new_status = @my_module.my_module_status
Do you really need this? Don't you have new status already?

2020-09-01 09:14 UTC, urbanrotnik commented on config/initializers/extends.rb
> +           *146..148],
@okriuchykhin  Should be `146` and `147` included here?

2020-09-01 09:43 UTC, aignatov-bio requested changes

2020-09-01 09:43 UTC, aignatov-bio commented on app/controllers/my_modules_controller.rb
> +    old_status = @my_module.my_module_status
Just store id

2020-09-01 09:54 UTC, aignatov-bio approved these changes

2020-09-01 10:33 UTC, aignatov-bio approved these changes

2020-09-01 10:33 UTC, merged