Add info of the locked task to the View status flow modal [SCI-5007]
biosistemika/scinote-web pull request #2860
Opened 2020-09-22 08:25 UTC by mlorb

#### Check [electronic_signatures](https://gitlab.com/biosistemika/scinote/addons/electronic_signatures/-/merge_requests/109)
Jira ticket: [SCI-xxxx](https://biosistemika.atlassian.net/browse/SCI-xxxx)

### What was done
Implication description was added.

2020-09-22 08:27 UTC, aignatov-bio requested changes

2020-09-22 08:27 UTC, aignatov-bio commented on app/views/my_modules/modals/_status_flow_modal_body.html.erb
> +        <%= implication_description %>
Why so complex?

2020-09-23 08:10 UTC, aignatov-bio requested changes

2020-09-23 08:10 UTC, aignatov-bio commented on app/views/my_modules/modals/_status_flow_modal_body.html.erb
> +          <%= implication.description %>
Newline?

2020-09-23 08:12 UTC, mlorb commented on app/views/my_modules/modals/_status_flow_modal_body.html.erb
> +          <%= implication.description %>
no, it should be the same line

2020-09-23 08:15 UTC, aignatov-bio approved these changes

2020-09-23 08:19 UTC, merged