Add mark for active filters [SCI-5085]
biosistemika/scinote-web pull request #2905
Opened 2020-10-20 14:47 UTC by urbanrotnik

Jira ticket: [SCI-5085](https://biosistemika.atlassian.net/browse/SCI-5085)

### What was done
Add a red dot for active filters

2020-10-22 13:51 UTC, aignatov-bio requested changes

2020-10-22 13:51 UTC, aignatov-bio commented on app/assets/stylesheets/dashboard/current_tasks.scss
> +      width: 7px;
User em here

2020-10-23 12:04 UTC, urbanrotnik commented on app/assets/stylesheets/dashboard/current_tasks.scss
> +      width: 7px;
Damit ems :D

2020-10-25 14:38 UTC, aignatov-bio approved these changes

2020-10-25 15:07 UTC, merged