Update repositories sidebar [SCI-5329]
biosistemika/scinote-web pull request #3031
Opened 2020-12-24 14:22 UTC by aignatov-bio

Jira ticket: [SCI-5329](https://biosistemika.atlassian.net/browse/SCI-5329)

### What was done
Update repositories sidebar

2021-01-04 21:08 UTC, mlorb requested changes
Nice work, just some small comments. :tada:

2021-01-04 21:08 UTC, mlorb commented on app/assets/stylesheets/partials/_sidebar.scss
> +        height: 4em;
Icons used to be smaller (18px)

2021-01-04 21:10 UTC, aignatov-bio commented on app/assets/stylesheets/partials/_sidebar.scss
> +        height: 4em;
It is the size of a container for icon

2021-01-04 21:13 UTC, aignatov-bio commented on app/assets/stylesheets/partials/_sidebar.scss
> +      padding-left: 3em;
archive icon not fitted otherwise

2021-01-05 08:22 UTC, aignatov-bio commented on app/assets/stylesheets/partials/_sidebar.scss
> +      padding-left: 3em;
otherwise, if you have a long repository name it will hover icon

2021-01-06 08:22 UTC, mlorb requested changes

2021-01-06 08:22 UTC, mlorb commented on app/assets/stylesheets/partials/_sidebar.scss
> +    .create-new-repository {
Remove also css.

2021-01-06 09:01 UTC, mlorb approved these changes

2021-01-06 09:13 UTC, merged