[WIP] Fix CSS for missing icons [SCI-5513]
biosistemika/scinote-web pull request #3195
Opened 2021-03-02 12:28 UTC by urbanrotnik

Jira ticket: [SCI-5513](https://biosistemika.atlassian.net/browse/SCI-5513)

### What was done
Do not merge/review.

2021-03-04 14:10 UTC, urbanrotnik commented
@aignatov-bio please test PDF on your local machine with this fix.

2021-03-08 09:18 UTC, aignatov-bio approved these changes

2021-03-08 11:19 UTC, aignatov-bio requested changes
In print mode font awesome icons not visible
In PDF report office icons not visible

2021-03-12 11:22 UTC, aignatov-bio approved these changes

2021-03-12 12:58 UTC, merged