Implement saving repository filters [SCI-6230]
biosistemika/scinote-web pull request #3748
Opened 2021-12-20 11:44 UTC by artoscinote

Jira ticket: [SCI-6230](https://biosistemika.atlassian.net/browse/SCI-6230)

### What was done
_In a sentence or two describe what was done, focus on the tech aspect_

#### ToDo:
_(Optional) If you have discovered an oppurtunity for refactor or another task that was not part of the jira issue, please write it here_

### Note:
_(Optional) Note any other remarks, problems you were facing during the development, suggestion etc_

2021-12-21 22:12 UTC, aignatov-bio requested changes

2021-12-21 22:12 UTC, aignatov-bio commented on app/assets/javascripts/repositories/show.js
> +  function initFilterSaving() {
Maybe try without form? This looks overcomplicated, maybe just 2 independent ajax requests?

2021-12-30 16:56 UTC, okriuchykhin commented on app/views/repository_table_filters/create.js.erb
> +<% if flash[:error] %>
Try to avoid .js.erb files

2022-01-05 13:57 UTC, aignatov-bio approved these changes

2022-01-05 14:02 UTC, merged