Add step orderable elements controller [SCI-6711]
biosistemika/scinote-web pull request #4034
Opened 2022-04-19 13:43 UTC by okriuchykhin

Jira ticket: [SCI-6711](https://biosistemika.atlassian.net/browse/SCI-6711)

### What was done
Add step orderable elements controller [SCI-6711]

2022-04-20 08:58 UTC, aignatov-bio requested changes
Will we also migrate here TinyMCE images? Now they belong to step. And I think some updates for the TinyMceAssets controller and MarvinJS controller/service, we have all checks with Step as the object.

2022-04-25 13:57 UTC, artoscinote commented
Could we call this just StepElement? I think this Orderable part is a bit redundant here.

2022-05-04 09:06 UTC, okriuchykhin commented
> Could we call this just StepElement? I think this Orderable part is a bit redundant here.

But it clearly describes purpose of this model

2022-05-04 09:25 UTC, aignatov-bio requested changes

2022-05-04 09:25 UTC, aignatov-bio commented on app/controllers/step_orderable_elements_controller.rb
> +      element_to_swap = @step.step_orderable_elements.find_by(id: params[:new_position])
I think we do not swap elements. We just move one element to the new position and all elements between old and new positions must be moved up/down depending on direction.

2022-08-10 08:10 UTC, closed without merging

2022-08-10 08:10 UTC, okriuchykhin commented
Obsolete